version: "3"

services:

  web:
    container_name: app-web
    image: app-next
    build:
      context: ./web/
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: