name: Deploy Server
on:
    push:
        branches:
            - main

jobs:
    job1:
        name: Deploy Server
        runs-on: ubuntu-latest

        steps:
          - name: Deploy
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd ${{ secrets.SERVER_DEPLOY_DIR }}
                    git pull origin main
                    docker compose down -v --rmi all
                    sudo systemctl restart opensns_front.service